name: CI Staging workflow

on:
  pull_request_target:
    types:
      - closed
    branches: [ "main" ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout git Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Check if re-test is needed
        id: test-check
        uses: zvigrinberg/git-retest-checkup-action@v1.1
        with:
          base-ref: ${{ github.base_ref }}
          pr-ref: ${{ github.head_ref }}
          file-pattern-regex: "^src/.*"



      - name: Install Java
        env:
          RETEST_IS_NECESSARY: ${{ steps.test-check.outputs.retest-is-needed}}
          TRIGGERING_FILE: ${{ steps.test-check.outputs.triggering-file}}
        run: |
          if [[ $RETEST_IS_NECESSARY == "true" ]]; then
             echo "re-test was triggered, triggering changed file - $TRIGGERING_FILE"
             mvn clean install
          else
             mvn clean install -DskipTests=true
          fi
